artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Pascalihub/Project_data/raw/main/flights%20data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

 
data_transformation:
  root_dir: artifacts/data_transformation
  data_train_path: artifacts/data_ingestion/Train_data
  preprocessor_path: artifacts/data_transformation/preprocessors.pkl


model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/Train_data
  model: artifacts/data_ingestion/model